package tc.oc.pgm.features;

import tc.oc.pgm.xml.Node;

/**
 * Implemented by all proxies generated by {@link FeatureDefinitionContext}.
 *
 * Can be used to detect references, and get the ID of the reference.
 */
public interface FeatureReference extends FeatureProxy {

    Node referenceNode();

    Class<? extends FeatureDefinition> referenceType();
}
